In [1]:
import pandas as pd
import numpy as np

In [2]:
# loading iris dataset from sklearn
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [3]:
X = iris.data
y = iris.target

In [4]:
X[0:3], y[0:3]

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2]]),
 array([0, 0, 0]))

In [5]:
# one hot encoding with keras
from keras.utils import to_categorical
y = to_categorical(y)
y.shape

(150, 3)

In [6]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=42)

In [7]:
# scaling the features into [0,1] interval with MinMaxScaler
# fitting the model with only train data and transforming both train and test data with training parameters
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [8]:
# creating an ANN model with 2 hidden layers
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu')) # layer 1
model.add(Dense(8, input_dim=4, activation='relu')) # layer 2
model.add(Dense(3, activation='softmax')) # output layer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [9]:
# fitting the model
model.fit(scaled_X_train, y_train, epochs=150, verbose=2) # verbose: level of the reporting detail

Epoch 1/150
4/4 - 0s - loss: 1.0958 - accuracy: 0.3400
Epoch 2/150
4/4 - 0s - loss: 1.0911 - accuracy: 0.3400
Epoch 3/150
4/4 - 0s - loss: 1.0878 - accuracy: 0.4700
Epoch 4/150
4/4 - 0s - loss: 1.0855 - accuracy: 0.4500
Epoch 5/150
4/4 - 0s - loss: 1.0833 - accuracy: 0.4900
Epoch 6/150
4/4 - 0s - loss: 1.0811 - accuracy: 0.5400
Epoch 7/150
4/4 - 0s - loss: 1.0792 - accuracy: 0.5600
Epoch 8/150
4/4 - 0s - loss: 1.0770 - accuracy: 0.5900
Epoch 9/150
4/4 - 0s - loss: 1.0747 - accuracy: 0.6100
Epoch 10/150
4/4 - 0s - loss: 1.0723 - accuracy: 0.6100
Epoch 11/150
4/4 - 0s - loss: 1.0696 - accuracy: 0.6100
Epoch 12/150
4/4 - 0s - loss: 1.0669 - accuracy: 0.6200
Epoch 13/150
4/4 - 0s - loss: 1.0638 - accuracy: 0.6300
Epoch 14/150
4/4 - 0s - loss: 1.0607 - accuracy: 0.6400
Epoch 15/150
4/4 - 0s - loss: 1.0573 - accuracy: 0.6400
Epoch 16/150
4/4 - 0s - loss: 1.0540 - accuracy: 0.6400
Epoch 17/150
4/4 - 0s - loss: 1.0504 - accuracy: 0.6500
Epoch 18/150
4/4 - 0s - loss: 1.0466 - accuracy: 0.6500
E

Epoch 147/150
4/4 - 0s - loss: 0.3672 - accuracy: 0.9200
Epoch 148/150
4/4 - 0s - loss: 0.3646 - accuracy: 0.9200
Epoch 149/150
4/4 - 0s - loss: 0.3612 - accuracy: 0.9300
Epoch 150/150
4/4 - 0s - loss: 0.3591 - accuracy: 0.9300


In [10]:
# predicting probability outputs
model.predict(scaled_X_test)

array([[2.72369031e-02, 5.54528832e-01, 4.18234229e-01],
       [9.75624859e-01, 2.31313575e-02, 1.24379760e-03],
       [2.97618302e-04, 1.70314401e-01, 8.29388022e-01],
       [1.66967753e-02, 5.06631434e-01, 4.76671815e-01],
       [1.36488788e-02, 4.85392183e-01, 5.00958979e-01],
       [9.60569024e-01, 3.68064679e-02, 2.62448471e-03],
       [5.77227958e-02, 6.05688095e-01, 3.36589158e-01],
       [1.39229093e-03, 2.72371560e-01, 7.26236105e-01],
       [7.89148174e-03, 3.58895093e-01, 6.33213401e-01],
       [4.22794446e-02, 5.83666444e-01, 3.74054104e-01],
       [3.85246868e-03, 3.76388580e-01, 6.19758964e-01],
       [9.57913578e-01, 3.89530137e-02, 3.13344132e-03],
       [9.72872674e-01, 2.56035980e-02, 1.52383791e-03],
       [9.62504864e-01, 3.48838903e-02, 2.61119055e-03],
       [9.78479564e-01, 2.04177499e-02, 1.10268593e-03],
       [1.57443322e-02, 5.45047402e-01, 4.39208180e-01],
       [1.09987310e-03, 2.43668616e-01, 7.55231440e-01],
       [4.67415750e-02, 5.71321

In [11]:
# predicting class outputs
y_pred = np.argmax(model.predict(scaled_X_test), axis=-1)
y_pred

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [12]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
print('Accuracy score ')
print(accuracy_score(y_pred, y_test.argmax(axis=1)))
print('------ ')
print('Confusion matrix ')
print(confusion_matrix(y_pred, y_test.argmax(axis=1)))
print('------ ')
print('Classification report ')
print(classification_report(y_pred, y_test.argmax(axis=1)))

Accuracy score 
0.96
------ 
Confusion matrix 
[[19  0  0]
 [ 0 13  0]
 [ 0  2 16]]
------ 
Classification report 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.87      1.00      0.93        13
           2       1.00      0.89      0.94        18

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.97      0.96      0.96        50



In [13]:
model.metrics_names

['loss', 'accuracy']

In [14]:
model.evaluate(x=scaled_X_test,y=y_test)

2/2 [==============================] - 0s 1ms/step - loss: 0.3132 - accuracy: 0.9600


[0.3132283091545105, 0.9599999785423279]

In [15]:
#saving the model for later usage
model.save('myfirstmodel.h5')

In [16]:
# loading a model and using it as an existing one
from keras.models import load_model
loaded_model = load_model('myfirstmodel.h5')
loaded_model.predict(scaled_X_test)

array([[2.72369031e-02, 5.54528832e-01, 4.18234229e-01],
       [9.75624859e-01, 2.31313575e-02, 1.24379760e-03],
       [2.97618302e-04, 1.70314401e-01, 8.29388022e-01],
       [1.66967753e-02, 5.06631434e-01, 4.76671815e-01],
       [1.36488788e-02, 4.85392183e-01, 5.00958979e-01],
       [9.60569024e-01, 3.68064679e-02, 2.62448471e-03],
       [5.77227958e-02, 6.05688095e-01, 3.36589158e-01],
       [1.39229093e-03, 2.72371560e-01, 7.26236105e-01],
       [7.89148174e-03, 3.58895093e-01, 6.33213401e-01],
       [4.22794446e-02, 5.83666444e-01, 3.74054104e-01],
       [3.85246868e-03, 3.76388580e-01, 6.19758964e-01],
       [9.57913578e-01, 3.89530137e-02, 3.13344132e-03],
       [9.72872674e-01, 2.56035980e-02, 1.52383791e-03],
       [9.62504864e-01, 3.48838903e-02, 2.61119055e-03],
       [9.78479564e-01, 2.04177499e-02, 1.10268593e-03],
       [1.57443322e-02, 5.45047402e-01, 4.39208180e-01],
       [1.09987310e-03, 2.43668616e-01, 7.55231440e-01],
       [4.67415750e-02, 5.71321

In [17]:
model.metrics_names

['loss', 'accuracy']